name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Asegúrate de que esto coincida con el nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install mkdocs mkdocs-material
      working-directory: primer-project

    - name: Build the MkDocs website
      run: mkdocs build
      working-directory: primer-project

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./primer-project/site
